apiVersion: v1
kind: Service
metadata:
  name: {{ include "ci-cd-demo.fullname" . }}
  labels:
    {{- include "ci-cd-demo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ include "ci-cd-demo.name" . }}
