# values.yaml
replicaCount: 1

image:
  repository: ghcr.io/gilikl/cicd-demo
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 5000



resources: {}
nodeSelector: {}
tolerations: []
