name: CI/CD

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main


jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: run_test
              uses: actions/setup-python@v5              
              with:
                python-version: '3.11' 
            - run: pip install --upgrade pip && pip install -r requirements.txt
            - run: pytest
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: login to github container registery
              uses: docker/login-action@v3
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}
            - name: Set lowercase image name
              run: |
                IMAGE_NAME=$(echo "ghcr.io/${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
                echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV
        
          
            - name: Build and push
              uses: docker/build-push-action@v6
              with:
                context: .
                push: true
                tags: ghcr.io/${{github.repository}}:latest


